name: Notify Slack on PR Creation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        id: send_notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#your-channel",
              "text": "A new pull request has been created: *${{ github.event.pull_request.title }}*",
              "attachments": [
                {
                  "fallback": "View the pull request on GitHub",
                  "actions": [
                    {
                      "type": "button",
                      "text": "View PR",
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Extract TS from Response
        run: |
          echo "${{ steps.send_notification.outputs.response }}" | jq -r '.ts' > slack_message_ts.txt

      - name: Archive Slack Message TS
        uses: actions/upload-artifact@v2
        with:
          name: slack-message-ts
          path: slack_message_ts.txt
